# Generated by Django 6.0.3 on 2026-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Progetto')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Immagine di Copertina')),
                ('technologies', models.CharField(max_length=255, verbose_name='Tecnologie (separate da virgola)')),
                ('project_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Progetto Live')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Repository GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine Visualizzazione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
