# Generated by Django 6.0.3 on 2026-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo Servizio')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('icon_name', models.CharField(help_text="Usa il nome dell'icona da Lucide React", max_length=50, verbose_name='Nome Icona (es. code, layout)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine Visualizzazione')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['order'],
            },
        ),
    ]
