# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/ilariadiliberto.com
cert = /etc/letsencrypt/live/ilariadiliberto.com/cert.pem
privkey = /etc/letsencrypt/live/ilariadiliberto.com/privkey.pem
chain = /etc/letsencrypt/live/ilariadiliberto.com/chain.pem
fullchain = /etc/letsencrypt/live/ilariadiliberto.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8a533dade08819197191924e3a9e0b28
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
