server {
    server_name ilariadiliberto.com 15.161.54.252;
    add_header X-Frame-Options "SAMEORIGIN" always;
 add_header X-Content-Type-Options "nosniff" always;
 add_header Referrer-Policy "strict-origin-when-cross-origin" always;
 add_header X-XSS-Protection "1; mode=block" always;


# 1. Il Frontend
    location / {
	root /home/ubuntu/portfolio/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
	root /home/ubuntu/portfolio/dist;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # 2. I File Statici del Backend (CSS e JS dell'Admin)
    location /static/ {
        alias /home/ubuntu/portfolio/backend/staticfiles/;
    }

    # 3. Il Backend (Le API e l'admin)
location /api {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://unix:/run/gunicorn/socket;
}

    location /admin {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://unix:/run/gunicorn/socket;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ilariadiliberto.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ilariadiliberto.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.ilariadiliberto.com) {
        # CAMBIA QUESTA RIGA QUI SOTTO (togli $host e metti il dominio pulito):
        return 301 https://ilariadiliberto.com$request_uri;
    } # managed by Certbot

    if ($host = ilariadiliberto.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name ilariadiliberto.com www.ilariadiliberto.com 15.161.54.252;
    return 404; # managed by Certbot
}
