# Generated by Django 6.0.3 on 2026-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Mittente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inviato il')),
            ],
            options={
                'verbose_name': 'Messaggio di Contatto',
                'verbose_name_plural': 'Messaggi di Contatto',
                'ordering': ['-created_at'],
            },
        ),
    ]
