# Generated by Django 6.0.6 on 2026-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='azienda',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Azienda/Progetto'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(default='', max_length=100, verbose_name='Budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sito_web',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sito Web/Social'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Messaggio'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oggetto'),
        ),
    ]
