# Generated by Django 6.0.6 on 2026-06-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmessage_azienda_contactmessage_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='azienda',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sito_web',
        ),
    ]
