# Generated by Django 6.0.3 on 2026-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ilaria Diliberto', max_length=100, verbose_name='Nome Completo')),
                ('title', models.CharField(default='UX Engineer & Cloud Specialist', max_length=100, verbose_name='Titolo Professionale')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Foto Profilo')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Curriculum Vitae (PDF)')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Località')),
                ('email', models.EmailField(default='hello@ilariadiliberto.com', max_length=254, verbose_name='Email di Contatto')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
            ],
            options={
                'verbose_name': 'Informazioni Personali',
                'verbose_name_plural': 'Informazioni Personali',
            },
        ),
    ]
