# Generated by Django 6.0.3 on 2026-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Post')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('content', models.TextField(verbose_name='Contenuto (Markdown)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Immagine di Copertina')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tag (separati da virgola)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Pubblicato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-created_at'],
            },
        ),
    ]
